
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------



-------------------------------- DOWNLOADING RAW DATA---------------------------
DROP TABLE #XXX

SELECT SURVEY_ID, ACT, STATUS, USER_ID, PROJECT, DATE_TRANSFERRED, SURVEY_DATE, 
PERIOD_DAY = CASE 
		WHEN PROJECT = 5555
		THEN (CASE WHEN SUBSTRING(SURVEY_DATE,7,4) > LEFT(PERIOD_,4) THEN SUBSTRING(SURVEY_DATE,7,4) ELSE LEFT(PERIOD_,4) END) +
				SUBSTRING(SURVEY_DATE,4,2) + LEFT(SURVEY_DATE,2)
		ELSE PERIOD_ + '00' 
				END  ,PERIOD_ ,NOTE AS VARCHAR(50)
INTO #XXX
FROM SURVEY_DATABASE..SURVEY_5555
WHERE PROJECT IN (5555) AND SURVEY_ID NOT IN( SELECT SURVEY_ID FROM RI.DBO.SOURCE_DATA) AND PERIOD_='202005'
ORDER BY PERIOD_,SURVEY_DATE


-----IF YOU HAVE ALREADY REPORTED A SURVEY ALREADY IN YOUR PREVIOUS REPORTS-------------------

BEGIN TRAN
DELETE #XXX
WHERE SURVEY_ID IN(	SELECT SURVEY_ID 
					FROM DATA_5555) 

COMMIT -- IF YOU WANT TO COMMIT USE THIS
/			
ROLLBACK -- IF YOU WANT TO ROLLBACK USE THIS


--ADDING A REFERENCE FIELD
ALTER TABLE #XXX ADD REFERENCE INT IDENTITY(1,1)


---APPLYING DATA CLEANING

---CLEANING THE DUPLICATIONS IF THERE IS ANY IN A MONTH ---
DROP TABLE DUPLICATIONS

UPDATE #XXX
SET ACT=0  ,NOTE='DUPLICATE_FORM'
WHERE SURVEY_ID IN
				(SELECT MAX(SURVEY_ID)
				FROM #XXX
				WHERE PERMON='202005' AND LOCATION_ID IN(
													  SELECT LOCATION_ID
													  FROM #XXX  
													  WHERE ACT=1 AND PERMON='202005' 
													  GROUP BY LOCATION_ID 
													  HAVING COUNT(*)>1))


---DELETING SURVEYS OTHER THAN ACTIVE STATUS
DELETE #XXX
WHERE ACT<>1


--------------UPLOADING RECENT MONTH DATA TO THE MAIN REPORTING TABLE FROM TEMPORARY TABLE--------

INSERT INTO SOURCE_DATA
SELECT SURVEY_ID, 1 ACTIVE, AUDITOR, PROJECT, DATE_TRANSFERRED, SURVEY_DATE, PERIOD_DAY, PERIOD_ ,NOTE
FROM #XXX
WHERE ACT=1 AND PERMON='202005'AND SURVEY_ID NOT IN (SELECT SURVEY_ID FROM SOURCE_DATA)

