


--------INNER JOIN VS FROM QUERY

--LETS SAY THESE ARE OUR DATA TABLES
SELECT USER_ID, NAME, SURNAME, ADRESS, COUNTRY, AGE
FROM USER

SELECT USER_ID,ID , CAMPANY_ID, COMPANY_NAME, DEPARTMENT
FROM COMPANIES



--THESE BOTH QUERY GIVES THE SAME RESULT
--1)
SELECT U.USER_ID, U.NAME, U.SURNAME, U.ADRESS, U.COUNTRY, U.AGE, C.ID, C.CAMPANY_ID, C.COMPANY_NAME, C.DEPARTMENT
FROM USER U, COMPANIES C
WHERE U.USER_ID=C.USER_ID
AND AGE BETWEEN 18 AND 50


--2)
SELECT U.USER_ID, U.NAME, U.SURNAME, U.ADRESS, U.COUNTRY, U.AGE, C.ID, C.CAMPANY_ID, C.COMPANY_NAME, C.DEPARTMENT
FROM USER U
INNER JOIN COMPANIES C
ON U.USER_ID=C.USER_ID
WHERE AGE BETWEEN 18 AND 50



---AS A NOTE, THERE ARE ALSO 'LEFT JOIN' AND 'RIGHT JOIN' COMMANDS IN USE FOR MERGING DATA FROM MORE THAN 1 TABLE. BUT RESULTS ARE DIFFERENT THAN THE QUERIES ABOVE.
---FOR LEFT JOIN, ALL RECORDS IN THE LEFT TABLE COMES DIRECTLY BUT RIGHT TABLE DATA COMES WHEN IT MACTHES WITH THE LEFT TABLE
---FOR RIGHT JOIN, ALL RECORDS IN THE RIGHT TABLE COMES DIRECTLY BUT LEFT TABLE DATA COMES WHEN IT MACTHES WITH THE RIGHT TABLE
