USE [ATTRIB05]
GO

/****** Object:  StoredProcedure [dbo].[PROJECT_SCORE_CALCULATION]    Script Date: 17/02/2020 11:48:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO








CREATE PROCEDURE [dbo].[PROJECT_SCORE_CALCULATION]

@PERIOD_STARTED 		VARCHAR(10),
@PERIOD_ENDED			VARCHAR(10)
AS





IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID (N'[DBO].[TEMP_PROJECT_SRC]') AND OBJECTPROPERTY(ID, N'ISUSERTABLE') = 1)
DROP TABLE [DBO].[TEMP_PROJECT_SRC]

IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID (N'[DBO].[TEMP_PR_RD]') AND OBJECTPROPERTY(ID, N'ISUSERTABLE') = 1)
DROP TABLE [DBO].[TEMP_PR_RD]


SELECT *
INTO TEMP_PROJECT_SRC
FROM PROJECT_VIEW_SRC_DATA
WHERE  PERIOD>=@PERIOD_STARTED AND PERIOD<=@PERIOD_ENDED

SELECT * 
INTO TEMP_PR_RD
FROM PROJECT_VIEW_RWD_DATA
WHERE  PERIOD>=@PERIOD_STARTED AND PERIOD<=@PERIOD_ENDED



-------Some Project Base Arrangements
UPDATE TEMP_PR_RD
SET ATTRIB05='OPPONENT'
WHERE ATTRIB01='SHELF' AND ATTRIB05 NOT IN('OUR_CUSTOMER_NAME')




------------PENETRATION CRITERS

---------WE KNOW ALREADEY SUM(SCORE_TARGET)=100---------------

DELETE PROJECT_SCORE_DATA
WHERE ID IN( SELECT ID 
			 FROM TEMP_PROJECT_SRC )
AND CRITER_CODE IN('SR_001','SR_002','SR_003')


INSERT INTO PROJECT_SCORE_DATA
(ID,SCORE_PERIOD,CRITER_CODE,VAL,SCORE,SCORE_TARGET)
SELECT ID,SCORE_PERIOD,CRITER_CODE,1 VAL,SUM(SCORE_X) SCORE,SUM(TARGET_X) SCORE_TARGET
FROM (
		SELECT X.*,MAIN_DATA=CASE WHEN Y.MAIN_DATA IS NULL THEN 0 ELSE Y.MAIN_DATA END,
			   SCORE_X=X.SCORE*(CASE WHEN Y.MAIN_DATA IS NULL THEN 0 ELSE Y.MAIN_DATA END),
			   TARGET_X=X.SCORE*NEEDED
		FROM (
				SELECT X.ID,Y.*
				FROM TEMP_PROJECT_SRC X,
					(
						SELECT SCORE_PERIOD,CATEGORY,CRITER_CODE,SCORE,COUNT(*) NEEDED
						FROM CUSTOMER_SCORES
						WHERE MAIN_CRITER='PENETRATION'
						GROUP BY SCORE_PERIOD,CATEGORY,CRITER_CODE,SCORE 
					) Y
				WHERE X.SCORE_PERIOD=Y.SCORE_PERIOD
			) X 
LEFT OUTER JOIN (
		SELECT ID,SCORE_PERIOD,CATEGORY,SCORE,COUNT(*) MAIN_DATA
		FROM (
				SELECT X.ID,X.SCORE_PERIOD,Y.SCORE,Y.CATEGORY
				FROM TEMP_PR_RD X,CUSTOMER_SCORES Y
				WHERE X.ATTRIB01='PENETRATION'
				AND Y.MAIN_CRITER='PENETRATION'
				AND X.SCORE_PERIOD=Y.SCORE_PERIOD	
			   ) X
		GROUP BY ID,SCORE_PERIOD,CATEGORY,SCORE
		   ) Y
ON X.ID=Y.ID AND X.SCORE_PERIOD=Y.SCORE_PERIOD AND X.CATEGORY=Y.CATEGORY AND  X.SCORE=Y.SCORE
) X
GROUP BY ID,SCORE_PERIOD,CRITER_CODE

PRINT '--------------- PENETRATION SCORES ARE UPLOADED ----------------'



------------------------- CONTROLS

DECLARE @ERROR INT

SELECT @ERROR = ( SELECT COUNT(*) CNT FROM PROJECT_SCORE_DATA GROUP BY ID HAVING SUM(SCORE_TARGET)<>100 )


IF (@ERROR<>0)
	BEGIN 
		PRINT '!!! THERE IS A PROBLEM IN THE REPORT - CHECK IT !!!'
	END 
ELSE 
	BEGIN
		PRINT '--------- REPORT OK - WELL DONE -----------' 
	END 


GO


