USE [DG]
GO

/****** Object:  View [dbo].[PROJECT_VIEW]    Script Date: 17/02/2020 11:46:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[PROJECT_VIEW]
AS
SELECT     PRJ.ID, PRJ.STORE_ID,LIST.STORE_NAME,PRJ.QUARTERS,PRJ.LATTITUDE,PRJ.LONGTITUDE,
           LIST.PRESELLER_CODE,LIST.PRESELLER,LIST.CITY_CODE,LIST.CITY,LIST.REGION_CODE,LIST.REGION,LIST.MANAGER_CODE,LIST.MANAGER
FROM       PROJECT_DATA PRJ,PROJECT_LIST LIST
WHERE  PRJ.STORE_ID = LIST.STORE_ID AND PRJ.ACT=1 AND LIST.ACT=1




GO


